### PR TITLE
Updated packages for Laravel 8 support

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
There are currently collisions between the package and Laravel 8 which are resolved by this PR.

### CODE REVIEW

**Comment by saff3t** [comment]
Upgrade required package guzzlehttp/guzzle 7.0.1 but your package require ^6.3
Any plan for change it?

**Comment by freearhey** [comment]
@saff3t Yes, of course. I just need some free time to check everything out before releasing.

**Comment by saff3t** [comment]
> @saff3t Yes, of course. I just need some free time to check everything out before releasing.

I'm waiting for update to Laravel 8. I can't update now, because guzzlehttp version conflict.

**Comment by MrKrisKrisu** [comment]
Same for me. My PullRequest will resolve the GuzzleHTTP conflict.

**Comment by JamesStark-Yorkshire** [comment]
Same here. Hope it could be resolve soon.

**Comment by freearhey** [comment]
@MrKrisKrisu Thank you for your help!

I have just published an updated version of the package, now the error should go away.

**Pull request merged**
